  
version: 0.2

phases:
  install:
    commands:
      - docker login -u umang2608 -p Umang@123
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
     
      - docker build -t dotnetbuild:1 .
      - docker tag dotnetbuild:1 umang2608/dotnetbuild:1 
      - docker push umang2608/dotnetbuild:1
      
artifacts:
  files:
    - '**/*'
