  
version: 0.2

phases:
  install:
    commands:
      - dotnet restore
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - dotnet build
      - dotnet publish
artifacts:
  files:
    - '**/*'
