  
version: 0.2

phases:
  install:
    commands:
      - dotnet restore
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - docker build -t dotnetbuild:1 .
      - docker tag dotnetbuild:1 umang2608/dotnetbuild:1 
      
artifacts:
  files:
    - '**/*'
